language: node_js
node_js:
- 6.3.0
- 10
after_success:
- 'cat ./coverage/lcov.info | ./node_modules/.bin/coveralls'
deploy:
  provider: npm
  email: mrstebouk@gmail.com
  api_key: $API_KEY
  skip_cleanup: true
  on:
    tags: true
    repo: mrstebo/fakergem
